<?php
			$optionsArray = array( 'totals' => array( 'udp_id' => array( 'totalsType' => '' ),
'udp_usu_id' => array( 'totalsType' => '' ),
'email_profissional' => array( 'totalsType' => '' ),
'avaliacao_usuarios' => array( 'totalsType' => '' ),
'sobre_profissional' => array( 'totalsType' => '' ),
'resumo_formacao' => array( 'totalsType' => '' ),
'yt_code_apresentacao' => array( 'totalsType' => '' ),
'diferencial_profissional' => array( 'totalsType' => '' ),
'atendimento_presencial' => array( 'totalsType' => '' ),
'atendimento_online' => array( 'totalsType' => '' ),
'mini_curriculo' => array( 'totalsType' => '' ),
'resumo_formacao_academica' => array( 'totalsType' => '' ),
'resumo_formacao_cursos' => array( 'totalsType' => '' ),
'curriculo_lattes' => array( 'totalsType' => '' ),
'nome_empresa' => array( 'totalsType' => '' ),
'cnpj' => array( 'totalsType' => '' ),
'ramo_empresa' => array( 'totalsType' => '' ),
'tipo_empresa' => array( 'totalsType' => '' ),
'cep_profissional' => array( 'totalsType' => '' ),
'endereco_profissional_rua' => array( 'totalsType' => '' ),
'endereco_profissional_numero' => array( 'totalsType' => '' ),
'endereco_profissional_complemento' => array( 'totalsType' => '' ),
'endereco_profissional_latitude' => array( 'totalsType' => '' ),
'endereco_profissional_longitude' => array( 'totalsType' => '' ),
'pais_empresa' => array( 'totalsType' => '' ),
'estado_empresa' => array( 'totalsType' => '' ),
'municipio_empresa' => array( 'totalsType' => '' ),
'udp_deletado' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'udp_id',
'udp_usu_id',
'email_profissional',
'avaliacao_usuarios',
'sobre_profissional',
'resumo_formacao',
'yt_code_apresentacao',
'diferencial_profissional',
'atendimento_presencial',
'atendimento_online',
'mini_curriculo',
'resumo_formacao_academica',
'resumo_formacao_cursos',
'curriculo_lattes',
'nome_empresa',
'cnpj',
'ramo_empresa',
'tipo_empresa',
'cep_profissional',
'endereco_profissional_rua',
'endereco_profissional_numero',
'endereco_profissional_complemento',
'endereco_profissional_latitude',
'endereco_profissional_longitude',
'pais_empresa',
'estado_empresa',
'municipio_empresa',
'udp_deletado' ),
'exportFields' => array( 'udp_id',
'udp_usu_id',
'email_profissional',
'avaliacao_usuarios',
'sobre_profissional',
'resumo_formacao',
'yt_code_apresentacao',
'diferencial_profissional',
'atendimento_presencial',
'atendimento_online',
'mini_curriculo',
'resumo_formacao_academica',
'resumo_formacao_cursos',
'curriculo_lattes',
'nome_empresa',
'cnpj',
'ramo_empresa',
'tipo_empresa',
'cep_profissional',
'endereco_profissional_rua',
'endereco_profissional_numero',
'endereco_profissional_complemento',
'endereco_profissional_latitude',
'endereco_profissional_longitude',
'pais_empresa',
'estado_empresa',
'municipio_empresa',
'udp_deletado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'udp_id' => array( 'export_field' ),
'udp_usu_id' => array( 'export_field1' ),
'email_profissional' => array( 'export_field2' ),
'avaliacao_usuarios' => array( 'export_field3' ),
'sobre_profissional' => array( 'export_field4' ),
'resumo_formacao' => array( 'export_field5' ),
'yt_code_apresentacao' => array( 'export_field6' ),
'diferencial_profissional' => array( 'export_field7' ),
'atendimento_presencial' => array( 'export_field8' ),
'atendimento_online' => array( 'export_field9' ),
'mini_curriculo' => array( 'export_field10' ),
'resumo_formacao_academica' => array( 'export_field11' ),
'resumo_formacao_cursos' => array( 'export_field12' ),
'curriculo_lattes' => array( 'export_field13' ),
'nome_empresa' => array( 'export_field14' ),
'cnpj' => array( 'export_field15' ),
'ramo_empresa' => array( 'export_field16' ),
'tipo_empresa' => array( 'export_field17' ),
'cep_profissional' => array( 'export_field18' ),
'endereco_profissional_rua' => array( 'export_field19' ),
'endereco_profissional_numero' => array( 'export_field20' ),
'endereco_profissional_complemento' => array( 'export_field21' ),
'endereco_profissional_latitude' => array( 'export_field22' ),
'endereco_profissional_longitude' => array( 'export_field23' ),
'pais_empresa' => array( 'export_field24' ),
'estado_empresa' => array( 'export_field25' ),
'municipio_empresa' => array( 'export_field26' ),
'udp_deletado' => array( 'export_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'udp_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'udp_usu_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'email_profissional',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'avaliacao_usuarios',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'sobre_profissional',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'resumo_formacao',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'yt_code_apresentacao',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'diferencial_profissional',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'atendimento_presencial',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'atendimento_online',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'mini_curriculo',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'resumo_formacao_academica',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'resumo_formacao_cursos',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'curriculo_lattes',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'nome_empresa',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cnpj',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'ramo_empresa',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'tipo_empresa',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'cep_profissional',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'endereco_profissional_rua',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'endereco_profissional_numero',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'endereco_profissional_complemento',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'endereco_profissional_latitude',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'endereco_profissional_longitude',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'pais_empresa',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'estado_empresa',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'municipio_empresa',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'udp_deletado',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>