<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'usu_id',
'nome',
'sobrenome',
'senha',
'email',
'email_validado',
'permissao',
'tipo_usuario',
'plano_tipo',
'data_in',
'data_primeiro_acesso',
'data_ultimo_acesso',
'cpf',
'avatar',
'sexo',
'info_inicial',
'pais',
'estado',
'municipio',
'cep',
'rua',
'numero',
'complemento',
'telefone_celular_principal',
'telefone_celular_secundario',
'telefone_residencial',
'telefone_comercial',
'code_trocar_senha',
'deletado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'usu_id' => array( 'import_field' ),
'nome' => array( 'import_field1' ),
'sobrenome' => array( 'import_field2' ),
'senha' => array( 'import_field3' ),
'email' => array( 'import_field4' ),
'email_validado' => array( 'import_field5' ),
'permissao' => array( 'import_field6' ),
'tipo_usuario' => array( 'import_field7' ),
'plano_tipo' => array( 'import_field8' ),
'data_in' => array( 'import_field9' ),
'data_primeiro_acesso' => array( 'import_field10' ),
'data_ultimo_acesso' => array( 'import_field11' ),
'cpf' => array( 'import_field12' ),
'avatar' => array( 'import_field13' ),
'sexo' => array( 'import_field14' ),
'info_inicial' => array( 'import_field15' ),
'pais' => array( 'import_field16' ),
'estado' => array( 'import_field17' ),
'municipio' => array( 'import_field18' ),
'cep' => array( 'import_field19' ),
'rua' => array( 'import_field20' ),
'numero' => array( 'import_field21' ),
'complemento' => array( 'import_field22' ),
'telefone_celular_principal' => array( 'import_field23' ),
'telefone_celular_secundario' => array( 'import_field24' ),
'telefone_residencial' => array( 'import_field25' ),
'telefone_comercial' => array( 'import_field26' ),
'code_trocar_senha' => array( 'import_field27' ),
'deletado' => array( 'import_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'usu_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'nome',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'sobrenome',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'senha',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'email_validado',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'permissao',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'tipo_usuario',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'plano_tipo',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'data_in',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'data_primeiro_acesso',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'data_ultimo_acesso',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cpf',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'avatar',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'sexo',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'info_inicial',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'pais',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'estado',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'municipio',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'cep',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'rua',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'numero',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'complemento',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'telefone_celular_principal',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'telefone_celular_secundario',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'telefone_residencial',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'telefone_comercial',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'code_trocar_senha',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'deletado',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>