<?php
			$optionsArray = array( 'totals' => array( 'usu_id' => array( 'totalsType' => '' ),
'nome' => array( 'totalsType' => '' ),
'sobrenome' => array( 'totalsType' => '' ),
'senha' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'email_validado' => array( 'totalsType' => '' ),
'permissao' => array( 'totalsType' => '' ),
'tipo_usuario' => array( 'totalsType' => '' ),
'plano_tipo' => array( 'totalsType' => '' ),
'data_in' => array( 'totalsType' => '' ),
'data_primeiro_acesso' => array( 'totalsType' => '' ),
'data_ultimo_acesso' => array( 'totalsType' => '' ),
'cpf' => array( 'totalsType' => '' ),
'avatar' => array( 'totalsType' => '' ),
'sexo' => array( 'totalsType' => '' ),
'info_inicial' => array( 'totalsType' => '' ),
'pais' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'municipio' => array( 'totalsType' => '' ),
'cep' => array( 'totalsType' => '' ),
'rua' => array( 'totalsType' => '' ),
'numero' => array( 'totalsType' => '' ),
'complemento' => array( 'totalsType' => '' ),
'telefone_celular_principal' => array( 'totalsType' => '' ),
'telefone_celular_secundario' => array( 'totalsType' => '' ),
'telefone_residencial' => array( 'totalsType' => '' ),
'telefone_comercial' => array( 'totalsType' => '' ),
'code_trocar_senha' => array( 'totalsType' => '' ),
'deletado' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'usu_id',
'nome',
'sobrenome',
'senha',
'email',
'email_validado',
'permissao',
'tipo_usuario',
'plano_tipo',
'data_in',
'data_primeiro_acesso',
'data_ultimo_acesso',
'cpf',
'avatar',
'sexo',
'info_inicial',
'pais',
'estado',
'municipio',
'cep',
'rua',
'numero',
'complemento',
'telefone_celular_principal',
'telefone_celular_secundario',
'telefone_residencial',
'telefone_comercial',
'code_trocar_senha',
'deletado' ),
'exportFields' => array( 'usu_id',
'nome',
'sobrenome',
'senha',
'email',
'email_validado',
'permissao',
'tipo_usuario',
'plano_tipo',
'data_in',
'data_primeiro_acesso',
'data_ultimo_acesso',
'cpf',
'avatar',
'sexo',
'info_inicial',
'pais',
'estado',
'municipio',
'cep',
'rua',
'numero',
'complemento',
'telefone_celular_principal',
'telefone_celular_secundario',
'telefone_residencial',
'telefone_comercial',
'code_trocar_senha',
'deletado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'usu_id' => array( 'export_field' ),
'nome' => array( 'export_field1' ),
'sobrenome' => array( 'export_field2' ),
'senha' => array( 'export_field3' ),
'email' => array( 'export_field4' ),
'email_validado' => array( 'export_field5' ),
'permissao' => array( 'export_field6' ),
'tipo_usuario' => array( 'export_field7' ),
'plano_tipo' => array( 'export_field8' ),
'data_in' => array( 'export_field9' ),
'data_primeiro_acesso' => array( 'export_field10' ),
'data_ultimo_acesso' => array( 'export_field11' ),
'cpf' => array( 'export_field12' ),
'avatar' => array( 'export_field13' ),
'sexo' => array( 'export_field14' ),
'info_inicial' => array( 'export_field15' ),
'pais' => array( 'export_field16' ),
'estado' => array( 'export_field17' ),
'municipio' => array( 'export_field18' ),
'cep' => array( 'export_field19' ),
'rua' => array( 'export_field20' ),
'numero' => array( 'export_field21' ),
'complemento' => array( 'export_field22' ),
'telefone_celular_principal' => array( 'export_field23' ),
'telefone_celular_secundario' => array( 'export_field24' ),
'telefone_residencial' => array( 'export_field25' ),
'telefone_comercial' => array( 'export_field26' ),
'code_trocar_senha' => array( 'export_field27' ),
'deletado' => array( 'export_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'usu_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'nome',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'sobrenome',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'senha',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'email_validado',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'permissao',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'tipo_usuario',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'plano_tipo',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'data_in',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'data_primeiro_acesso',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'data_ultimo_acesso',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cpf',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'avatar',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'sexo',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'info_inicial',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'pais',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'estado',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'municipio',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cep',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'rua',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'numero',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'complemento',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'telefone_celular_principal',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'telefone_celular_secundario',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'telefone_residencial',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'telefone_comercial',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'code_trocar_senha',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'deletado',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>