<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Nome',
'Email',
'Senha',
'Endereco',
'Bairro',
'Cidade',
'Estado',
'Cep',
'Celular',
'Tel_Residencial',
'Data_Inicio',
'Sexo',
'Sintomas',
'Tratamento',
'CPF',
'RG' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Nome' => array( 'import_field1' ),
'Email' => array( 'import_field2' ),
'Senha' => array( 'import_field3' ),
'Endereco' => array( 'import_field4' ),
'Bairro' => array( 'import_field5' ),
'Cidade' => array( 'import_field6' ),
'Estado' => array( 'import_field7' ),
'Cep' => array( 'import_field8' ),
'Celular' => array( 'import_field9' ),
'Tel_Residencial' => array( 'import_field10' ),
'Data_Inicio' => array( 'import_field11' ),
'Sexo' => array( 'import_field12' ),
'Sintomas' => array( 'import_field13' ),
'Tratamento' => array( 'import_field14' ),
'CPF' => array( 'import_field' ),
'RG' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field',
'import_field15' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field' => 'grid',
'import_field15' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field',
'import_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'Nome',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Email',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Senha',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Endereco',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Bairro',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Cidade',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Cep',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Celular',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Tel_Residencial',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Data_Inicio',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Sexo',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Sintomas',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Tratamento',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'CPF',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'RG',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>